name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WORKLOAD_IDENTITY_PROVIDER: projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ vars.WORKLOAD_IDENTITY_PROVIDER_ID }}
  IMAGE: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GIT_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build -t ${{ env.IMAGE }} .

      - name: Push image
        run: docker push ${{ env.IMAGE }}

      - name: Deploy
        run: |
          gcloud run deploy ${{ vars.SERVICE_NAME }} \
          --image ${{ env.IMAGE }} \
          --region ${{ vars.GCP_REGION }} \
          --port=8080 \
          --service-account=${{ vars.APP_SERVICE_ACCOUNT }} \
          --set-env-vars=APIFY_ACTOR_ID=aAaDnGZgNwHm4mzcl \
          --set-secrets=APIFY_API_TOKEN=apify-api-token:1,OPENAI_API_KEY=openai-api-key:1 \
          --memory=512Mi
